### ISSUE TITLE
Divide bookings to upcoming and past bookings on All bookings page

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#105]
We should see future bookings and past bookings separately just like in the "my page"

**Comment by andri-yta** [comment]
This comment is not related to this issue. 

On the smaller screen, the content of the navigation bar is overflow if the staff has a long email address. Since we will be working on dividing the _All Bookings_ page, we might as well work on fixing the navigation bar. This could be done similarly like the naisten-linja public site by making (1) hamburger menu for smaller screen and/or (2) submenu for _Bookings_-related page.
