### ISSUE TITLE
Make vapaaehtoiset.naistenlinja.fi mobile-friendly [7.5h, time spent 10h+2h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#72]

**Comment by Marilakeus** [comment]
Should we first test mobile responsiveness and then analyze the quick fixes from the bigger issues?

**Comment by nathandao** [comment]
Some design work will be needed for this as well. As the page was first intended to be used only on desktop.

The booking calendar view is probably the most critical page, as it is used the most by the volunteers. Adding horizontal scrolling support for the booking calendar on mobile (instead of squeezing everything to fit the device's width) seems to be the most straightforward way.
